### ISSUE TITLE
Can SNPbinner use for other bi-parents mapping populations?

### ISSUE THREAD

**Issue by xiekunwhy** [solgenomics/snpbinner#3]
Hi,

Like title, can SNPbinner use for other bi-parents mapping populations like F2, BCsFt and DH?

Cheers,
Kun.

**Comment by itaygonda** [comment]
We have tested it with an F2 tomato population (resequencing data) that was very noisy and it worked well. Yet, required different parameters from defaults that were set for RILs. Can't see why it won't work for other population types. My best suggestion is to play with parameters, especially -p and -l/-r, and plot them using visualize. Rarely different chromosome require different parameters.
Cheers,
Itay

**Comment by xiekunwhy** [comment]
Hi Itay, thank you for your reply.
When I use module bins, it always tell me argument -o/--output is required
